config.py: Put newtime in a tuple
File "/usr/lib/enigma2/python/Components/config.py", line 710, in getMulti
     (value, mPos) = self.genText()
   File "/usr/lib/enigma2/python/Components/config.py", line 1062, in genText
     value = strftime(config.usage.time.short.value.replace("%-I", "%_I").replace("%-H", "%_H"), newtime)
 TypeError: Tuple or struct_time argument required