GraphMultiEpg.py: Put now_time in a tuple
File "/usr/lib/enigma2/python/Plugins/Extensions/GraphMultiEPG/GraphMultiEpg.py", line 48, in <module>
    config.misc.graph_mepg.prime_time = ConfigClock(default =  mktime(now_time))
TypeError: Tuple or struct_time argument required